# Generated by Django 5.1.1 on 2024-09-28 14:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextdocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contextdocument',
            name='valid_till',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='taxforminstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxformvalidation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
