# Generated by Django 5.1.1 on 2024-09-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_generator', '0002_contextdocument_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxforminstance',
            name='data',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='taxforminstance',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('validated', 'Validated'), ('posted', 'Posted')], max_length=20),
        ),
        migrations.AlterField(
            model_name='taxforminstance',
            name='xml',
            field=models.TextField(null=True),
        ),
    ]
