# Generated by Django 5.1.1 on 2024-09-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_generator', '0004_taxform_system_prompt_alter_taxforminstance_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxform',
            name='xml_template',
            field=models.TextField(null=True),
        ),
    ]
