# Generated by Django 5.1.1 on 2024-09-29 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0003_interaction_response_json_and_more'),
        ('xml_generator', '0005_taxform_xml_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxforminstance',
            name='source_interaction',
        ),
        migrations.AddField(
            model_name='taxforminstance',
            name='source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='assistant.session'),
        ),
    ]
