# Generated by Django 5.1.1 on 2024-09-29 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_generator', '0006_remove_taxforminstance_source_interaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxforminstance',
            name='user_designation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
