# Generated by Django 5.1.1 on 2024-09-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xml_generator', '0007_alter_taxforminstance_user_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxformvalidation',
            name='valid_till',
            field=models.DateField(blank=True, null=True),
        ),
    ]
