# Generated by Django 5.1.1 on 2024-09-28 14:04

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JednostkaAdministracyjna',
            fields=[
                ('stan_na', models.DateField()),
                ('aktywny', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=50)),
                ('nazwa_dod', models.CharField(max_length=50)),
                ('typ', models.CharField(max_length=3)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('wojewodztwa', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='RodzajMiejscowosci',
            fields=[
                ('stan_na', models.DateField()),
                ('aktywny', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Miejscowosc',
            fields=[
                ('stan_na', models.DateField()),
                ('aktywny', models.BooleanField(default=False)),
                ('symbol', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('nazwa', models.CharField(max_length=100)),
                ('jednostka', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt.jednostkaadministracyjna')),
                ('miejscowosc_nadrzedna', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teryt.miejscowosc')),
                ('rodzaj_miejscowosci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt.rodzajmiejscowosci')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('miasta', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Ulica',
            fields=[
                ('stan_na', models.DateField()),
                ('aktywny', models.BooleanField(default=False)),
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('symbol_ulicy', models.CharField(max_length=10)),
                ('cecha', models.CharField(max_length=10)),
                ('nazwa_1', models.CharField(max_length=100)),
                ('nazwa_2', models.CharField(blank=True, max_length=100, null=True)),
                ('miejscowosc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teryt.miejscowosc')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
