# Generated by Django 5.1.1 on 2024-09-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teryt', '0002_jednostkaadministracyjna_gmi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jednostkaadministracyjna',
            name='typ',
            field=models.CharField(max_length=20),
        ),
    ]
