# Generated by Django 5.1.1 on 2024-09-28 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='ongoing', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
