# Generated by Django 5.1.1 on 2024-09-28 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0002_session_status_session_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='response_json',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='status',
            field=models.CharField(choices=[('ongoing', 'Ongoing'), ('finished', 'Finished'), ('aborted', 'Aborted')], default='ongoing', max_length=20),
        ),
    ]
